- .eslintrc.js
- apps/cms/package.json
- apps/website/package.json
- commitlint.config.js
- package.json
- packages/blog-components/.eslintignore
- packages/blog-components/.eslintrc.js
- packages/blog-components/jest.setup.js
- packages/blog-components/package.json
- packages/blog-components/scripts/build-storybook.sh
- packages/blog-components/scripts/build.sh
- packages/blog-components/scripts/clean.sh
- packages/blog-components/scripts/lint.sh
- packages/blog-components/scripts/storybook.sh
- packages/blog-components/scripts/test.sh
- packages/blog-components/scripts/watch.sh
- packages/blog-components/src/Gif/Gif.test.tsx
- packages/blog-components/src/Icons/Icons.stories.tsx
- packages/blog-components/src/index.ts
- scripts/common/lint.sh
- yarn.lock
- fix lint command for blog-components
- remove incorrect export
- add scripts files to blog components package
> Upgrade dependencies and more

- apps/cms/exports/graphql/schema.graphql
- apps/website/src/locales/en.json
- apps/website/src/locales/pt.json
- apps/website/src/screens/Blog/BlogPage.tsx
- apps/website/src/screens/Blog/components/FeaturedImage/FeaturedImage.tsx
- apps/website/src/types/api/posts.ts
> Issue#8 unsplash

- apps/website/src/components/MenuBar/MenuBar.tsx
- apps/website/src/components/MenuBar/useHideMenu.ts
> fix(website): menubar toggle when scroll all the way up

- apps/website/next.config.js
> chore(website): upgrade next to webpack 5

- apps/website/src/components/PostCardWrapper.tsx
> fix(website): use next/image on postcard

- apps/website/package.json
- apps/website/src/components/MenuBar/MenuBar.tsx
- apps/website/src/components/MenuBar/components/LanguageSwitch/LanguageSwitch.tsx
- apps/website/src/components/MenuBar/components/ThemeSwitch/ThemeSwitch.tsx
- yarn.lock
Closes https://github.com/raulfdm/raulmelo-studio/issues/15
> Upgrade component lib v4

- apps/cms/api/post-tag/documentation/1.0.0/post-tag.json
- apps/cms/api/post-tag/models/post-tag.settings.json
- apps/cms/api/til/config/routes.json
- apps/cms/api/til/controllers/til.js
- apps/cms/api/til/documentation/1.0.0/til.json
- apps/cms/api/til/models/til.js
- apps/cms/api/til/models/til.settings.json
- apps/cms/api/til/services/til.js
- apps/cms/exports/graphql/schema.graphql
- apps/cms/extensions/documentation/documentation/1.0.0/full_documentation.json
> feat: add "til" content type

- apps/website/src/components/MdxComponents/Headings/Headings.test.tsx
- apps/website/src/components/MdxComponents/Headings/Headings.tsx
- apps/website/src/styles/base.ts
The way I've styled before wasn't being applied.
> fix: icon links

- apps/website/src/components/PostBasic/PostBasic.tsx
- apps/website/src/locales/en.json
- apps/website/src/locales/pt.json
- apps/website/src/pages/tag/[slug].tsx
- apps/website/src/screens/Tag/TagPage.tsx
- apps/website/src/screens/Tag/types.ts
> feat: show tils on tag page

- packages/mdx-prism-2/.gitignore
- packages/mdx-prism-2/babel.config.js
- packages/mdx-prism-2/jest.config.js
- packages/mdx-prism-2/package.json
- packages/mdx-prism-2/rollup.config.js
- packages/mdx-prism-2/scripts/build.sh
- packages/mdx-prism-2/scripts/clean.sh
- packages/mdx-prism-2/scripts/dev.sh
- packages/mdx-prism-2/scripts/lint.sh
- packages/mdx-prism-2/scripts/prepare.sh
- packages/mdx-prism-2/scripts/test.sh
- packages/mdx-prism-2/src/__test__/test.js
- packages/mdx-prism-2/src/add-markers.js
- packages/mdx-prism-2/src/index.js
- packages/mdx-prism-2/src/map.js
- yarn.lock
To make it possible, I had to implement building steps with Rollup so I can consume (and also writing in) es6 and compile down to commonjs
> Upgrade Unist* dependencies to latest major version.

- packages/mdx-prism-2/package.json
- yarn.lock
BREAKING CHANGE: @rollup/plugin-node-resolve was upgraded from v11 to v13
> chore(deps): major dependency upgrade

- apps/website/src/components/templates/MdxPost/MdxPost.tsx
- apps/website/src/components/templates/MdxPost/components/Header/Header.tsx
- apps/website/src/locales/en.json
- apps/website/src/locales/pt.json
- apps/website/src/pages/uses.tsx
- apps/website/src/screens/BlogPost/BlogPost.tsx
- apps/website/src/screens/Uses/UsesPage.tsx
> feat: implement reading time for articles

- apps/website/next-env.d.ts
- apps/website/src/config/analytics.ts
- apps/website/src/pages/_app.tsx
- apps/website/src/pages/_document.tsx
> fix: move scripts from _document to _app

- package.json
- packages/mdx-prism-2/package.json
- packages/mdx-prism-2/rollup.config.js
- packages/mdx-prism-2/src/addMarkers/__tests__/helpers.test.ts
- packages/mdx-prism-2/src/mdxPrism/__test__/index.test.ts
- packages/mdx-prism-2/src/mdxPrism/mdxPrism.ts
- packages/mdx-prism-2/types/hast-util-to-string.d.ts
- yarn.lock
BREAKING CHANGE: upgrade major dependencies version
> chore(deps): upgrade deps

- apps/cms-sanity/package.json
- apps/cms-sanity/sanity.json
- apps/cms-sanity/schemas/customFields/divider.tsx
- pnpm-lock.yaml
> [Sanity] Add media browsing plugin

- .github/workflows/cms-deploy.yml
- .github/workflows/lambdas.yml
- .github/workflows/packages.yml
- .github/workflows/website.yml
> chore: use pnpm action image as ci

- apps/fitness-buddy/src/lib/components/Activity/Actvity.svelte
- apps/fitness-buddy/src/lib/components/Activity/activityStore.ts
- apps/fitness-buddy/src/lib/components/Activity/components/Clock.svelte
- apps/fitness-buddy/src/lib/components/Activity/components/ClockConfig.svelte
- apps/fitness-buddy/src/lib/components/Activity/components/Content.svelte
- apps/fitness-buddy/src/lib/components/Activity/components/DropSetCalculator.svelte
- apps/fitness-buddy/src/lib/components/Icons/FastForwardIcon.svelte
- apps/fitness-buddy/src/lib/components/Icons/RewindIcon.svelte
This PR:
- adds Drop-set calculator;
- adds rewind and fast forward of series;
- enhance overral styles;
> More fitness improvements

- apps/fitness-buddy/package.json
- apps/fitness-buddy/scripts/dev/typegen.sh
- apps/fitness-buddy/src/lib/components/BottomBar.svelte
- apps/fitness-buddy/src/lib/components/old/Activity/components/Clock.svelte
- apps/fitness-buddy/src/lib/components/old/Activity/components/Content.svelte
- apps/fitness-buddy/src/lib/components/old/Activity/components/DropSetCalculator.svelte
- apps/fitness-buddy/src/lib/components/old/Activity/components/TrainingInfo.svelte
- apps/fitness-buddy/src/lib/components/old/Activity/index.svelte
- apps/fitness-buddy/src/lib/stores/old/activity.ts
- apps/fitness-buddy/src/lib/stores/old/audio.ts
- apps/fitness-buddy/src/lib/stores/old/clockMachine.ts
- apps/fitness-buddy/src/routes/+page.server.ts
- apps/fitness-buddy/src/routes/+page.svelte
- apps/fitness-buddy/src/routes/new-training/+page.server.ts
- apps/fitness-buddy/src/routes/new-training/+page.svelte
- apps/fitness-buddy/src/routes/workout/[id]/+page.server.ts
- apps/fitness-buddy/src/routes/workout/[id]/+page.svelte
I don't have the time to finish the refactor. Meanwhile I still need to use the app so to avoid using an two versions, I brought back all the old clock files.
This code base is a mess but one day I'd have the time to fix it :)
> [Temp] Add back old training

- apps/fitness-buddy/package.json
- apps/fitness-buddy/src/lib/api.ts
- apps/fitness-buddy/src/lib/components/old/Activity/components/Content.svelte
- apps/fitness-buddy/src/lib/components/old/Activity/components/TrainingInfo.svelte
- apps/fitness-buddy/src/lib/components/old/Activity/index.svelte
- apps/fitness-buddy/src/routes/+layout.svelte
- apps/fitness-buddy/src/routes/workout/[id]/+page.svelte
After reverting the old activity approach, there was some bugs.
> fix: small bugs

- apps/website/next.config.js
- apps/website/package.json
- apps/website/scripts/build.sh
- apps/website/src/pages/_app.page.tsx
- apps/website/src/pages/_document.page.tsx
- pnpm-lock.yaml
Don't know if I've configured wrong but I'm no longer receiving analytics data.
> chore: revert partytown

- apps/website/config/babel.config.js
- apps/website/jest.config.js
- apps/website/next.config.js
- apps/website/package.json
- apps/website/src/components/PostBasic/PostBasic.tsx
- apps/website/src/components/ShareContent.tsx
- apps/website/src/components/Tags/Tags.test.tsx
- apps/website/src/components/Tags/Tags.tsx
- apps/website/src/pages/_app.page.tsx
- apps/website/src/styles/globals.css
- pnpm-lock.yaml
- renovate-config.js
> refactor: purge emotion

- packages/core/package.json
- packages/core/scripts/build.sh
- packages/core/vite.config.ts
- pnpm-lock.yaml
Related #2085
- Add `zod`
- refactor vite config to proper build
> refactor core lib

- packages/styles/lib/tailwind.config.cjs
- packages/ui/src/components/Highlight/Highlight.module.css
> Enhance inline highlight

- packages/core/package.json
- pnpm-lock.yaml
> remove unused dependencies

- apps/website/src/infrastructure/sanity/schemas/customFields/blockContentField.tsx
- apps/website/src/infrastructure/sanity/schemas/customFields/calloutField.tsx
- apps/website/src/infrastructure/sanity/schemas/customFields/index.ts
- apps/website/src/ui/PortableText/Callout/Callout.astro
- apps/website/src/ui/PortableText/Callout/index.ts
- apps/website/src/ui/PortableText/Callout/types.ts
- apps/website/src/ui/PortableText/PortableText.astro
- packages/core/src/utils/contentBlockToMarkdown.ts
> add info + note callout

- apps/website/src/infrastructure/i18n/locales/en.json
- apps/website/src/infrastructure/i18n/locales/pt.json
- apps/website/src/infrastructure/utils/url.ts
- apps/website/src/pages/[lang]/blog/[slug].astro
- apps/website/src/pages/[lang]/blog/index.astro
- apps/website/src/pages/[lang]/search/index.astro
- apps/website/src/pages/[lang]/tags/[tag].astro
- apps/website/src/pages/[lang]/tags/index.astro
- apps/website/src/pages/[lang]/til/[slug].astro
- apps/website/src/pages/[lang]/til/index.astro
- apps/website/src/ui/Breadcrumbs/Breadcrumb.svelte
- apps/website/src/ui/Breadcrumbs/Breadcrumbs.svelte
- apps/website/src/ui/Breadcrumbs/index.ts
- apps/website/src/ui/Breadcrumbs/types.ts
- apps/website/src/ui/layouts/Layout.astro
- apps/website/src/ui/layouts/PostLayout.astro
> Add bread crumb

- apps/website/src/ui/PortableText/Callout/Callout.astro
- apps/website/src/ui/PortableText/Callout/types.ts
> add new callout variation and tweak colors

- apps/website/src/infrastructure/sanity/schemas/blog/post.ts
- apps/website/src/infrastructure/sanity/schemas/blog/til.ts
- apps/website/src/pages/[lang]/blog/[slug].astro
- apps/website/src/pages/[lang]/til/[slug].astro
- packages/core/src/domains/posts/queryPostBySlug.ts
- packages/core/src/domains/posts/queryTilBySlug.ts
This PR adds "Related Posts" to blog post
> feat: add related posts

- apps/website/src/middleware.ts
- apps/website/src/pages/api/webhooks/update-algolia.ts
This PR fixes the api endpoints in conjunction with Astro Middleware
> fix middleware and endpoint

- apps/website/package.json
- apps/website/src/infrastructure/sanity/previewDocumentNode.ts
- pnpm-lock.yaml
> Update package versions in package.json and
